[versions]
spring-boot = "4.0.0"
spring-dependency-management = "1.1.7"
java-jwt = "4.4.0"
flyway = "10.17.0"
postgres = "42.7.4"
logback = "1.5.6"
junit = "5.10.3"
assertj = "3.26.3"
testcontainers = "1.20.1"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "spring-boot" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers", version.ref = "spring-boot" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-test", version.ref = "spring-boot" }
spring-boot-test-autoconfigure = { module = "org.springframework.boot:spring-boot-test-autoconfigure", version.ref = "spring-boot" }
spring-boot-webmvc-test = { module = "org.springframework.boot:spring-boot-webmvc-test", version.ref = "spring-boot" }
spring-boot-data-jpa-test = { module = "org.springframework.boot:spring-boot-data-jpa-test", version.ref = "spring-boot" }
spring-boot-jpa-test = { module = "org.springframework.boot:spring-boot-jpa-test", version.ref = "spring-boot" }
spring-boot-jdbc-test = { module = "org.springframework.boot:spring-boot-jdbc-test", version.ref = "spring-boot" }

java-jwt = { module = "com.auth0:java-jwt", version.ref = "java-jwt" }

flyway = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }

testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-pg = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
